// fcp_v2_assets/languages.js
// ไฟล์สำหรับเก็บคำแปลทั้งหมด

export const translations = {
    // English
    en: {
        appTitle: "Football Scoreboard Controller - V2.5",
        excel: "Excel",
        matchId: "ID:",
        load: "Load",
        teamA: "Team A",
        teamB: "Team B",
        edit: "Edit",
        editHint: "Edit name or add new line with /",
        ok: "OK",
        label1: "Label 1",
        label2: "Label 2",
        label3: "Label 3",
        swap: "Swap Teams",
        reset: "Reset",
        half: "Half",
        injuryTime: "Added Time",
        countdown: "Down",
        countdownHint: "Countdown Timer",
        resetToZeroHint: "Reset timer to 00:00",
        resetToStartHint: "Reset timer to configured start time",
        settings: "Settings",
        copy: "Copy",
        help: "Help",
        donate: "Donate",
        footerAppName: "OBS Dock UI Scoreboard",
        changelog: "Update Version 2.5",
        detailsTitle: "Announcement Text Settings",
        detailsDesc: "Create message using the tags below to pull data automatically.",
        tagsTitle: "Available Tags",
        tagsList: [
            { code: '&lt;TeamA&gt;', desc: '- Team A Name' },
            { code: '&lt;TeamB&gt;', desc: '- Team B Name' },
            { code: '&lt;score_team_a&gt;', desc: '- Team A Score' },
            { code: '&lt;score_team_b&gt;', desc: '- Team B Score' },
            { code: '&lt;time_counter&gt;', desc: '- Current Time (MM:SS)' },
            { code: '&lt;half_text&gt;', desc: '- Half (1st/2nd)' },
            { code: '&lt;label1&gt;', desc: '- Label 1 Text' },
            { code: '&lt;label2&gt;', desc: '- Label 2 Text' },
            { code: '&lt;label3&gt;', desc: '- Label 3 Text' },
        ],
        save: "Save",
        close: "Close",
        saveAndUpdate: "Save & Update",
        helpTitle: "How to Use",
        helpStep1: "1. Click the <i class='fas fa-folder-open'></i> icon to set your logo folder path. By default it is <code>C:/OBSAssets/logos</code>.",
        helpStep2: "2. Click <i class='fas fa-file-excel'></i> Excel button to select your data file.",
        helpStep3: "3. Select the desired Match ID and click <i class='fas fa-check'></i> Load.",
        sourcesTitle: "Required OBS Sources",
        sourcesList: [
            { code: 'Color_Team_A', desc: '- **Color Source** for Team A (Primary)' },
            { code: 'Color_Team_B', desc: '- **Color Source** for Team B (Primary)' },
            { code: 'Color_Team_A_2', desc: '- **Color Source** for Team A (Secondary)' },
            { code: 'Color_Team_B_2', desc: '- **Color Source** for Team B (Secondary)' },
            { code: 'logo_team_a', desc: '- **Image Source** for Team A Logo' },
            { code: 'logo_team_b', desc: '- **Image Source** for Team B Logo' },
            { code: 'name_team_a', desc: '- **Text (GDI+)** for Team A Name' },
            { code: 'name_team_b', desc: '- **Text (GDI+)** for Team B Name' },
            { code: 'score_team_a', desc: '- **Text (GDI+)** for Team A Score' },
            { code: 'score_team_b', desc: '- **Text (GDI+)** for Team B Score' },
            { code: 'label_1', desc: '- **Text (GDI+)** for Label 1' },
            { code: 'label_2', desc: '- **Text (GDI+)** for Label 2' },
            { code: 'label_3', desc: '- **Text (GDI+)** for Label 3' },
            { code: 'half_text', desc: '- **Text (GDI+)** for Half' },
            { code: 'time_counter', desc: '- **Text (GDI+)** for Timer' },
            { code: 'injury_time_text', desc: '- **Text (GDI+)** for Added Time (+1)' },
        ],
        understand: "Got it",
        donateTitle: "Support Us",
        donateThai: "For Thais (for Scoreboard)",
        donateForeign: "For Foreigners (Outside Thailand)",
        timeSettingsTitle: "Set Start Time",
        timeSettingsMinutes: "Minutes",
        timeSettingsSeconds: "Seconds",
        logoPathTitle: "Logo Folder Path",
        logoPathDesc: "The current logo folder path is:",
        logoPathHint: "Set logo folder path",
        changelogTitle: "Update History",
        changelogContent: `
            <ul class="changelog-list">
                <li>
                    <h5>Version 2.5</h5>
                    <ul>
                        <li>Moved the logo folder path setting into a dedicated popup.</li>
                        <li>Added a secondary color option for each team.</li>
                    </ul>
                </li>
                <li>
                    <h5>Version 2.4</h5>
                    <ul>
                        <li>Major UI overhaul for timer controls based on feedback.</li>
                        <li>Added a "Save & Update" button to apply time changes to the live timer immediately.</li>
                        <li>Improved the "Reset to Start Time" button's reliability.</li>
                    </ul>
                </li>
            </ul>`,
        toastLoadFileFirst: "Please upload a file first",
        toastMatchNotFound: "Match ID not found:",
        toastLoaded: "Loaded ID:",
        toastSuccess: "Success",
        toastSwapped: "Teams swapped",
        toastNoTextToCopy: "No text to copy",
        toastCopied: "Copied to clipboard",
        toastCopyFailed: "Copy failed",
        toastScoreReset: "Score reset",
        toastSaved: "Saved",
        toastObsError: "Failed to connect to OBS",
        toastInvalidTime: "Invalid time format. Please check minutes and seconds (0-59).",
        toastTimeSet: "Start time has been set and updated.",
    },
    // ภาษาไทย
    th: {
        appTitle: "โปรแกรมควบคุมสกอร์บอร์ดฟุตบอล - V2.5",
        excel: "Excel",
        matchId: "ID:",
        load: "โหลด",
        teamA: "ทีม A",
        teamB: "ทีม B",
        edit: "แก้ไข",
        editHint: "แก้ไขชื่อ หรือขึ้นบรรทัดใหม่ด้วยการใส่ /",
        ok: "ตกลง",
        label1: "ป้าย 1",
        label2: "ป้าย 2",
        label3: "ป้าย 3",
        swap: "สลับฝั่ง",
        reset: "รีเซ็ต",
        half: "ครึ่ง",
        injuryTime: "ทดเวลา",
        countdown: "นับถอยหลัง",
        countdownHint: "ตัวนับเวลาถอยหลัง",
        resetToZeroHint: "รีเซ็ตเวลาเป็น 00:00",
        resetToStartHint: "รีเซ็ตตามเวลาที่ตั้งค่า",
        settings: "ตั้งค่า",
        copy: "คัดลอก",
        help: "วิธีใช้",
        donate: "สนับสนุน",
        footerAppName: "OBS Dock UI Scoreboard",
        changelog: "อัปเดตเวอร์ชัน 2.5",
        detailsTitle: "ตั้งค่าข้อความประกาศ",
        detailsDesc: "สร้างข้อความโดยใช้ Tags ด้านล่างเพื่อดึงข้อมูลอัตโนมัติ",
        tagsTitle: "Tags ที่ใช้งานได้",
        tagsList: [
            { code: '&lt;TeamA&gt;', desc: '- ชื่อทีม A' },
            { code: '&lt;TeamB&gt;', desc: '- ชื่อทีม B' },
            { code: '&lt;score_team_a&gt;', desc: '- คะแนนทีม A' },
            { code: '&lt;score_team_b&gt;', desc: '- คะแนนทีม B' },
            { code: '&lt;time_counter&gt;', desc: '- เวลาปัจจุบัน (MM:SS)' },
            { code: '&lt;half_text&gt;', desc: '- ครึ่งเวลา (1st/2nd)' },
            { code: '&lt;label1&gt;', desc: '- ข้อความ Label 1' },
            { code: '&lt;label2&gt;', desc: '- ข้อความ Label 2' },
            { code: '&lt;label3&gt;', desc: '- ข้อความ Label 3' },
        ],
        save: "บันทึก",
        close: "ปิด",
        saveAndUpdate: "บันทึกและอัปเดต",
        helpTitle: "วิธีการใช้งาน",
        helpStep1: "1. กดปุ่ม <i class='fas fa-folder-open'></i> เพื่อตั้งค่าที่อยู่โฟลเดอร์โลโก้ (ค่าเริ่มต้นคือ <code>C:/OBSAssets/logos</code>)",
        helpStep2: "2. กดปุ่ม <i class='fas fa-file-excel'></i> Excel เพื่อเลือกไฟล์ข้อมูล",
        helpStep3: "3. เลือก Match ID ที่ต้องการ แล้วกด <i class='fas fa-check'></i> Load",
        sourcesTitle: "OBS Sources ที่ต้องมี",
        sourcesList: [
            { code: 'Color_Team_A', desc: '- **Color Source** สำหรับสีทีม A (สีหลัก)' },
            { code: 'Color_Team_B', desc: '- **Color Source** สำหรับสีทีม B (สีหลัก)' },
            { code: 'Color_Team_A_2', desc: '- **Color Source** สำหรับสีทีม A (สีรอง)' },
            { code: 'Color_Team_B_2', desc: '- **Color Source** สำหรับสีทีม B (สีรอง)' },
            { code: 'logo_team_a', desc: '- **Image Source** สำหรับโลโก้ทีม A' },
            { code: 'logo_team_b', desc: '- **Image Source** สำหรับโลโก้ทีม B' },
            { code: 'name_team_a', desc: '- **Text (GDI+)** สำหรับชื่อทีม A' },
            { code: 'name_team_b', desc: '- **Text (GDI+)** สำหรับชื่อทีม B' },
            { code: 'score_team_a', desc: '- **Text (GDI+)** สำหรับคะแนนทีม A' },
            { code: 'score_team_b', desc: '- **Text (GDI+)** สำหรับคะแนนทีม B' },
            { code: 'label_1', desc: '- **Text (GDI+)** สำหรับป้าย 1' },
            { code: 'label_2', desc: '- **Text (GDI+)** สำหรับป้าย 2' },
            { code: 'label_3', desc: '- **Text (GDI+)** สำหรับป้าย 3' },
            { code: 'half_text', desc: '- **Text (GDI+)** สำหรับครึ่งเวลา' },
            { code: 'time_counter', desc: '- **Text (GDI+)** สำหรับตัวนับเวลา' },
            { code: 'injury_time_text', desc: '- **Text (GDI+)** สำหรับทดเวลาบาดเจ็บ (+1)' },
        ],
        understand: "เข้าใจแล้ว",
        donateTitle: "ร่วมสนับสนุน",
        donateThai: "สำหรับคนไทย (ขึ้น Scoreboard)",
        donateForeign: "สำหรับนอกประเทศไทย",
        timeSettingsTitle: "ตั้งเวลาเริ่มต้น",
        timeSettingsMinutes: "นาที",
        timeSettingsSeconds: "วินาที",
        logoPathTitle: "ที่อยู่โฟลเดอร์โลโก้",
        logoPathDesc: "ที่อยู่โฟลเดอร์โลโก้ปัจจุบันคือ:",
        logoPathHint: "ตั้งค่าที่อยู่โฟลเดอร์โลโก้",
        changelogTitle: "ประวัติการอัปเดต",
        changelogContent: `
            <ul class="changelog-list">
                 <li>
                    <h5>เวอร์ชัน 2.5</h5>
                    <ul>
                        <li>ย้ายการตั้งค่าที่อยู่โฟลเดอร์โลโก้ไปไว้ใน Popup</li>
                        <li>เพิ่มความสามารถในการกำหนดสีที่สองสำหรับแต่ละทีม</li>
                    </ul>
                </li>
                <li>
                    <h5>เวอร์ชัน 2.4</h5>
                    <ul>
                        <li>ปรับปรุง UI ส่วนควบคุมเวลาครั้งใหญ่ตามที่ผู้ใช้แนะนำ</li>
                        <li>เพิ่มปุ่ม "บันทึกและอัปเดต" เพื่อให้แก้ไขและแสดงผลเวลาใหม่ทันที</li>
                        <li>ปรับปรุงการทำงานของปุ่ม "คืนค่าเวลา" ให้เสถียรขึ้น</li>
                    </ul>
                </li>
            </ul>`,
        toastLoadFileFirst: "โปรด Upload ไฟล์ก่อน",
        toastMatchNotFound: "ไม่พบ Match ID:",
        toastLoaded: "โหลด ID สำเร็จ:",
        toastSuccess: "สำเร็จ",
        toastSwapped: "สลับฝั่งทีมแล้ว",
        toastNoTextToCopy: "ไม่มีข้อความให้คัดลอก",
        toastCopied: "คัดลอกแล้ว",
        toastCopyFailed: "คัดลอกล้มเหลว",
        toastScoreReset: "รีเซ็ตคะแนนแล้ว",
        toastSaved: "บันทึกแล้ว",
        toastObsError: "เชื่อมต่อ OBS ไม่สำเร็จ",
        toastInvalidTime: "รูปแบบเวลาไม่ถูกต้อง กรุณาตรวจสอบนาทีและวินาที (0-59)",
        toastTimeSet: "ตั้งค่าและอัปเดตเวลาเริ่มต้นแล้ว",
    },
    // Korean
    ko: {
        appTitle: "축구 스코어보드 컨트롤러 - V2.5",
        excel: "엑셀",
        matchId: "ID:",
        load: "로드",
        teamA: "팀 A",
        teamB: "팀 B",
        edit: "수정",
        editHint: "이름을 수정하거나 /로 새 줄을 추가하세요",
        ok: "확인",
        label1: "레이블 1",
        label2: "레이블 2",
        label3: "레이블 3",
        swap: "팀 교체",
        reset: "재설정",
        half: "전/후반",
        injuryTime: "추가 시간",
        countdown: "카운트다운",
        countdownHint: "카운트다운 타이머",
        resetToZeroHint: "타이머를 00:00으로 재설정",
        resetToStartHint: "구성된 시작 시간으로 타이머 재설정",
        settings: "설정",
        copy: "복사",
        help: "도움말",
        donate: "후원",
        footerAppName: "OBS Dock UI 스코어보드",
        changelog: "업데이트 버전 2.5",
        detailsTitle: "공지 텍스트 설정",
        detailsDesc: "아래 태그를 사용하여 데이터를 자동으로 가져오는 메시지를 만드세요.",
        tagsTitle: "사용 가능한 태그",
        tagsList: [
            { code: '&lt;TeamA&gt;', desc: '- 팀 A 이름' },
            { code: '&lt;TeamB&gt;', desc: '- 팀 B 이름' },
            { code: '&lt;score_team_a&gt;', desc: '- 팀 A 점수' },
            { code: '&lt;score_team_b&gt;', desc: '- 팀 B 점수' },
            { code: '&lt;time_counter&gt;', desc: '- 현재 시간 (MM:SS)' },
            { code: '&lt;half_text&gt;', desc: '- 전/후반 (1st/2nd)' },
            { code: '&lt;label1&gt;', desc: '- 레이블 1 텍스트' },
            { code: '&lt;label2&gt;', desc: '- 레이블 2 텍스트' },
            { code: '&lt;label3&gt;', desc: '- 레이블 3 텍스트' },
        ],
        save: "저장",
        close: "닫기",
        saveAndUpdate: "저장 및 업데이트",
        helpTitle: "사용 방법",
        helpStep1: "1. <i class='fas fa-folder-open'></i> 아이콘을 클릭하여 로고 폴더 경로를 설정하세요. 기본값은 <code>C:/OBSAssets/logos</code>입니다.",
        helpStep2: "2. <i class='fas fa-file-excel'></i> 엑셀 버튼을 클릭하여 데이터 파일을 선택하세요.",
        helpStep3: "3. 원하는 경기 ID를 선택하고 <i class='fas fa-check'></i> 로드를 클릭하세요.",
        sourcesTitle: "필요한 OBS 소스",
        sourcesList: [
            { code: 'Color_Team_A', desc: '- 팀 A를 위한 **색상 소스** (기본)' },
            { code: 'Color_Team_B', desc: '- 팀 B를 위한 **색상 소스** (기본)' },
            { code: 'Color_Team_A_2', desc: '- 팀 A를 위한 **색상 소스** (보조)' },
            { code: 'Color_Team_B_2', desc: '- 팀 B를 위한 **색상 소스** (보조)' },
            { code: 'logo_team_a', desc: '- 팀 A 로고를 위한 **이미지 소스**' },
            { code: 'logo_team_b', desc: '- 팀 B 로고를 위한 **이미지 소스**' },
            { code: 'name_team_a', desc: '- 팀 A 이름을 위한 **텍스트 (GDI+)**' },
            { code: 'name_team_b', desc: '- 팀 B 이름을 위한 **텍스트 (GDI+)**' },
            { code: 'score_team_a', desc: '- 팀 A 점수를 위한 **텍스트 (GDI+)**' },
            { code: 'score_team_b', desc: '- 팀 B 점수를 위한 **텍스트 (GDI+)**' },
            { code: 'label_1', desc: '- 레이블 1을 위한 **텍스트 (GDI+)**' },
            { code: 'label_2', desc: '- 레이블 2를 위한 **텍스트 (GDI+)**' },
            { code: 'label_3', desc: '- 레이블 3을 위한 **텍스트 (GDI+)**' },
            { code: 'half_text', desc: '- 전/후반을 위한 텍스트 (GDI+)' },
            { code: 'time_counter', desc: '- 타이머를 위한 텍스트 (GDI+)' },
            { code: 'injury_time_text', desc: '- 추가 시간을 위한 **텍스트 (GDI+)** (+1)' },
        ],
        understand: "이해했습니다",
        donateTitle: "후원하기",
        donateThai: "태국인을 위해 (스코어보드용)",
        donateForeign: "외국인용 (태국 외)",
        timeSettingsTitle: "시작 시간 설정",
        timeSettingsMinutes: "분",
        timeSettingsSeconds: "초",
        logoPathTitle: "로고 폴더 경로",
        logoPathDesc: "현재 로고 폴더 경로는 다음과 같습니다:",
        logoPathHint: "로고 폴더 경로 설정",
        changelogTitle: "업데이트 내역",
        changelogContent: `
            <ul class="changelog-list">
                <li><h5>버전 2.5</h5>
                    <ul>
                        <li>로고 폴더 경로 설정을 전용 팝업으로 이동했습니다.</li>
                        <li>각 팀에 대한 보조 색상 옵션을 추가했습니다.</li>
                    </ul>
                </li>
                 <li><h5>버전 2.4</h5>
                    <ul>
                        <li>피드백에 따라 타이머 제어 UI가 크게 개편되었습니다.</li>
                        <li>시간 변경 사항을 즉시 적용하기 위해 "저장 및 업데이트" 버튼이 추가되었습니다.</li>
                        <li>"시작 시간으로 재설정" 버튼의 안정성이 향상되었습니다.</li>
                    </ul>
                </li>
            </ul>`,
        toastLoadFileFirst: "먼저 파일을 업로드하세요",
        toastMatchNotFound: "경기 ID를 찾을 수 없습니다:",
        toastLoaded: "ID 로드 성공:",
        toastSuccess: "성공",
        toastSwapped: "팀이 교체되었습니다",
        toastNoTextToCopy: "복사할 텍스트가 없습니다",
        toastCopied: "클립보드에 복사됨",
        toastCopyFailed: "복사 실패",
        toastScoreReset: "점수 재설정됨",
        toastSaved: "저장됨",
        toastObsError: "OBS 연결 실패",
        toastInvalidTime: "잘못된 시간 형식입니다. 분과 초(0-59)를 확인하세요.",
        toastTimeSet: "시작 시간이 설정 및 업데이트되었습니다.",
    },
    // Lao
    lo: {
        appTitle: "ໂຕຄວບຄຸມກະດານຄະແນນບານເຕະ - V2.5",
        excel: "Excel",
        matchId: "ID:",
        load: "ໂຫຼດ",
        teamA: "ທີມ A",
        teamB: "ທີມ B",
        edit: "ແກ້ໄຂ",
        editHint: "ແກ້ໄຂຊື່ ຫຼື ເພີ່ມແຖວໃໝ່ດ້ວຍ /",
        ok: "ຕົກລົງ",
        label1: "ປ້າຍ 1",
        label2: "ປ້າຍ 2",
        label3: "ປ້າຍ 3",
        swap: "ສลับຝັ່ງ",
        reset: "ຣີເຊັດ",
        half: "ເຄິ່ງ",
        injuryTime: "ທົດເວລາ",
        countdown: "ນັບຖອຍຫຼັງ",
        countdownHint: "ໂຕນັບເວລາຖອຍຫຼັງ",
        resetToZeroHint: "ຣີເຊັດເວລາເປັນ 00:00",
        resetToStartHint: "ຣີເຊັດເປັນເວລາເລີ່ມຕົ້ນທີ່ຕັ້ງໄວ້",
        settings: "ຕັ້ງຄ່າ",
        copy: "ສຳເນົາ",
        help: "ວິທີໃຊ້",
        donate: "ສະໜັບສະໜູນ",
        footerAppName: "OBS Dock UI Scoreboard",
        changelog: "ອັບເດດເວີຊັ່ນ 2.5",
        detailsTitle: "ຕັ້ງຄ່າຂໍ້ຄວາມປະກາດ",
        detailsDesc: "ສ້າງຂໍ້ຄວາມໂດຍໃຊ້ແທັກຂ້າງລຸ່ມເພື່ອດຶງຂໍ້ມູນອັດຕະໂນມັດ.",
        tagsTitle: "ແທັກທີ່ໃຊ້ໄດ້",
        tagsList: [
            { code: '&lt;TeamA&gt;', desc: '- ຊື່ທີມ A' },
            { code: '&lt;TeamB&gt;', desc: '- ຊື່ທີມ B' },
            { code: '&lt;score_team_a&gt;', desc: '- ຄະແນນທີມ A' },
            { code: '&lt;score_team_b&gt;', desc: '- ຄະແນນທີມ B' },
            { code: '&lt;time_counter&gt;', desc: '- ເວລາປັດຈຸບັນ (MM:SS)' },
            { code: '&lt;half_text&gt;', desc: '- ເຄິ່ງເວລາ (1st/2nd)' },
            { code: '&lt;label1&gt;', desc: '- ຂໍ້ຄວາມປ້າຍ 1' },
            { code: '&lt;label2&gt;', desc: '- ຂໍ້ຄວາມປ້າຍ 2' },
            { code: '&lt;label3&gt;', desc: '- ຂໍ້ຄວາມປ້າຍ 3' },
        ],
        save: "ບັນທຶກ",
        close: "ປິດ",
        saveAndUpdate: "ບັນທຶກ ແລະ ອັບເດດ",
        helpTitle: "ວິທີການໃຊ້ງານ",
        helpStep1: "1. ກົດໄອຄອນ <i class='fas fa-folder-open'></i> ເພື່ອຕັ້ງຄ່າທີ່ຢູ່ໂຟນເດີໂລໂກ້ (ຄ່າເລີ່ມຕົ້ນແມ່ນ <code>C:/OBSAssets/logos</code>).",
        helpStep2: "2. ກົດປຸ່ມ <i class='fas fa-file-excel'></i> Excel ເພື່ອເລືອກໄຟລ໌ຂໍ້ມູນ.",
        helpStep3: "3. ເລືອກ Match ID ທີ່ຕ້ອງການ ແລ້ວກົດ <i class='fas fa-check'></i> ໂຫຼດ.",
        sourcesTitle: "OBS Sources ທີ່ຕ້ອງມີ",
        sourcesList: [
            { code: 'Color_Team_A', desc: '- **Color Source** ສຳລັບສີທີມ A (ສີຫຼັກ)' },
            { code: 'Color_Team_B', desc: '- **Color Source** ສຳລັບສີທີມ B (ສີຫຼັກ)' },
            { code: 'Color_Team_A_2', desc: '- **Color Source** ສຳລັບສີທີມ A (ສີຮອງ)' },
            { code: 'Color_Team_B_2', desc: '- **Color Source** ສຳລັບສີທີມ B (ສີຮອງ)' },
            { code: 'logo_team_a', desc: '- **Image Source** ສຳລັບໂລໂກ້ທີມ A' },
            { code: 'logo_team_b', desc: '- **Image Source** ສຳລັບໂລໂກ້ທີມ B' },
            { code: 'name_team_a', desc: '- **Text (GDI+)** ສຳລັບຊື່ທີມ A' },
            { code: 'name_team_b', desc: '- **Text (GDI+)** ສຳລັບຊື່ທີມ B' },
            { code: 'score_team_a', desc: '- **Text (GDI+)** ສຳລັບຄະແນນທີມ A' },
            { code: 'score_team_b', desc: '- **Text (GDI+)** ສຳລັບຄະແນນທີມ B' },
            { code: 'label_1', desc: '- **Text (GDI+)** ສຳລັບປ້າຍ 1' },
            { code: 'label_2', desc: '- **Text (GDI+)** ສຳລັບປ້າຍ 2' },
            { code: 'label_3', desc: '- **Text (GDI+)** ສຳລັບປ້າຍ 3' },
            { code: 'half_text', desc: '- **Text (GDI+)** ສຳລັບເຄິ່ງເວລາ' },
            { code: 'time_counter', desc: '- **Text (GDI+)** ສຳລັບໂຕນັບເວລາ' },
            { code: 'injury_time_text', desc: '- **Text (GDI+)** ສຳລັບທົດເວລາບາດເຈັບ (+1)' },
        ],
        understand: "ເຂົ້າໃຈແລ້ວ",
        donateTitle: "ຮ່ວມສະໜັບສະໜູນ",
        donateThai: "ສຳລັບຄົນໄທ (ຂຶ້ນ Scoreboard)",
        donateForeign: "ສຳລັບຕ່າງປະເທດ",
        timeSettingsTitle: "ຕັ້ງເວລາເລີ່ມຕົ້ນ",
        timeSettingsMinutes: "ນາທີ",
        timeSettingsSeconds: "ວິນາທີ",
        logoPathTitle: "ທີ່ຢູ່ໂຟນເດີໂລໂກ້",
        logoPathDesc: "ທີ່ຢູ່ໂຟນເດີໂລໂກ້ປັດຈຸບັນແມ່ນ:",
        logoPathHint: "ຕັ້ງຄ່າທີ່ຢູ່ໂຟນເດີໂລໂກ້",
        changelogTitle: "ປະຫວັດການອັບເດດ",
        changelogContent: `
            <ul class="changelog-list">
                <li><h5>ເວີຊັ່ນ 2.5</h5>
                    <ul>
                        <li>ຍ້າຍການຕັ້ງຄ່າທີ່ຢູ່ໂຟນເດີໂລໂກ້ໄປໄວ້ໃນ Popup.</li>
                        <li>ເພີ່ມຕົວເລືອກສີທີສອງສຳລັບແຕ່ລະທີມ.</li>
                    </ul>
                </li>
                <li><h5>ເວີຊັ່ນ 2.4</h5>
                    <ul>
                        <li>ປັບປຸງ UI ຄວບຄຸມເວລາຕາມຄຳແນະນຳ.</li>
                        <li>ເພີ່ມປຸ່ມ "ບັນທຶກ ແລະ ອັບເດດ" ເພື່ອໃຊ້ການປ່ຽນແປງເວລາທັນທີ.</li>
                        <li>ປັບປຸງຄວາມໜ້າເຊື່ອຖືຂອງປຸ່ມ 'ຣີເຊັດເປັນເວລາເລີ່ມຕົ້ນ'.</li>
                    </ul>
                </li>
            </ul>`,
        toastLoadFileFirst: "ກະລຸນາອັບໂຫຼດໄຟລ໌ກ່ອນ",
        toastMatchNotFound: "ບໍ່ພົບ Match ID:",
        toastLoaded: "ໂຫຼດ ID ສຳເລັດ:",
        toastSuccess: "ສຳເລັດ",
        toastSwapped: "ສลับຝັ່ງທີມແລ້ວ",
        toastNoTextToCopy: "ບໍ່ມີຂໍ້ຄວາມໃຫ້ສຳເນົາ",
        toastCopied: "ສຳເນົາແລ້ວ",
        toastCopyFailed: "ສຳເນົາລົ້ມເຫຼວ",
        toastScoreReset: "ຣີເຊັດຄະແນນແລ້ວ",
        toastSaved: "ບັນທຶກແລ້ວ",
        toastObsError: "ເຊື່ອມຕໍ່ OBS ບໍ່ສຳເລັດ",
        toastInvalidTime: "ຮູບແບບເວລາບໍ່ຖືກຕ້ອງ. ກະລຸນາກວດສອບນາທີ ແລະ ວິນາທີ (0-59).",
        toastTimeSet: "ໄດ້ຕັ້ງ ແລະ ອັບເດດເວລາເລີ່ມຕົ້ນແລ້ວ.",
    },
    // Khmer (Cambodian)
    km: {
        appTitle: "កម្មវិធីបញ្ជាតារាងពិន្ទុបាល់ទាត់ - V2.5",
        excel: "Excel",
        matchId: "ID:",
        load: "ផ្ទុក",
        teamA: "ក្រុម A",
        teamB: "ក្រុម B",
        edit: "កែសម្រួល",
        editHint: "កែឈ្មោះ ឬបន្ថែមបន្ទាត់ថ្មីជាមួយ /",
        ok: "យល់ព្រម",
        label1: "ស្លាក ១",
        label2: "ស្លាក ២",
        label3: "ស្លាក ៣",
        swap: "ប្តូរក្រុម",
        reset: "កំណត់ឡើងវិញ",
        half: "តង់",
        injuryTime: "ម៉ោងបន្ថែម",
        countdown: "រាប់ថយក្រោយ",
        countdownHint: "កម្មវិធីកំណត់เวลារាប់ថอยหลัง",
        resetToZeroHint: "កំណត់เวลาឡើងវិញទៅ 00:00",
        resetToStartHint: "កំណត់เวลาឡើងវិញទៅពេលចាប់ផ្តើមដែលបានកំណត់",
        settings: "ការកំណត់",
        copy: "ចម្លង",
        help: "ជំនួយ",
        donate: "គាំទ្រ",
        footerAppName: "OBS Dock UI Scoreboard",
        changelog: "អัปដេតកំណែ 2.5",
        detailsTitle: "ការកំណត់អត្ថបទប្រកាស",
        detailsDesc: "បង្កើតសារដោយប្រើស្លាកខាងក្រោមដើម្បីទាញទិន្នន័យដោយស្វ័យប្រវត្តិ។",
        tagsTitle: "ស្លាកដែលមាន",
        tagsList: [
            { code: '&lt;TeamA&gt;', desc: '- ឈ្មោះក្រុម A' },
            { code: '&lt;TeamB&gt;', desc: '- ឈ្មោះក្រុម B' },
            { code: '&lt;score_team_a&gt;', desc: '- ពិន្ទុក្រុម A' },
            { code: '&lt;score_team_b&gt;', desc: '- ពិន្ទុក្រុម B' },
            { code: '&lt;time_counter&gt;', desc: '- ពេលវេលាបច្ចុប្បន្ន (MM:SS)' },
            { code: '&lt;half_text&gt;', desc: '- តង់ (1st/2nd)' },
            { code: '&lt;label1&gt;', desc: '- អត្ថបទស្លាក ១' },
            { code: '&lt;label2&gt;', desc: '- អត្ថបទស្លាក ២' },
            { code: '&lt;label3&gt;', desc: '- អត្ថបទស្លាក ៣' },
        ],
        save: "រក្សាទុក",
        close: "បិទ",
        saveAndUpdate: "រក្សាទុក & ធ្វើបច្ចុប្បន្នភាព",
        helpTitle: "របៀបប្រើ",
        helpStep1: "1. ចុចរូបតំណាង <i class='fas fa-folder-open'></i> ដើម្បីកំណត់ផ្លូវថតនិមិត្តសញ្ញារបស់អ្នក។ តាមលំនាំដើមវាគឺ <code>C:/OBSAssets/logos</code>។",
        helpStep2: "2. ចុចប៊ូតុង <i class='fas fa-file-excel'></i> Excel ដើម្បីជ្រើសរើសឯកសារទិន្នន័យ។",
        helpStep3: "3. ជ្រើសរើស Match ID ដែលចង់បាន ហើយចុច <i class='fas fa-check'></i> ផ្ទុក។",
        sourcesTitle: "OBS Sources ដែលត្រូវការ",
        sourcesList: [
            { code: 'Color_Team_A', desc: '- **Color Source** សម្រាប់ក្រុម A (ចម្បង)' },
            { code: 'Color_Team_B', desc: '- **Color Source** សម្រាប់ក្រុម B (ចម្បង)' },
            { code: 'Color_Team_A_2', desc: '- **Color Source** សម្រាប់ក្រុម A (បន្ទាប់បន្សំ)' },
            { code: 'Color_Team_B_2', desc: '- **Color Source** សម្រាប់ក្រុម B (បន្ទាប់បន្សំ)' },
            { code: 'logo_team_a', desc: '- **Image Source** សម្រាប់និមិត្តសញ្ញាក្រុម A' },
            { code: 'logo_team_b', desc: '- **Image Source** សម្រាប់និមិត្តសញ្ញាក្រុម B' },
            { code: 'name_team_a', desc: '- **Text (GDI+)** សម្រាប់ឈ្មោះក្រុម A' },
            { code: 'name_team_b', desc: '- **Text (GDI+)** សម្រាប់ឈ្មោះក្រុម B' },
            { code: 'score_team_a', desc: '- **Text (GDI+)** សម្រាប់ពិន្ទុក្រុម A' },
            { code: 'score_team_b', desc: '- **Text (GDI+)** សម្រាប់ពិន្ទុក្រុម B' },
            { code: 'label_1', desc: '- **Text (GDI+)** សម្រាប់ស្លាក ១' },
            { code: 'label_2', desc: '- **Text (GDI+)** សម្រាប់ស្លាក ២' },
            { code: 'label_3', desc: '- **Text (GDI+)** សម្រាប់ស្លាក ៣' },
            { code: 'half_text', desc: '- **Text (GDI+)** សម្រាប់តង់' },
            { code: 'time_counter', desc: '- **Text (GDI+)** សម្រាប់កម្មវិធីកំណត់เวลา' },
            { code: 'injury_time_text', desc: '- **Text (GDI+)** សម្រាប់ម៉ោងបន្ថែម (+1)' },
        ],
        understand: "យល់ហើយ",
        donateTitle: "គាំទ្រពួកយើង",
        donateThai: "សម្រាប់ជនជាតិថៃ (សម្រាប់តារាងពិន្ទុ)",
        donateForeign: "សម្រាប់ជនបរទេស (ក្រៅប្រទេសថៃ)",
        timeSettingsTitle: "កំណត់ម៉ោងចាប់ផ្តើម",
        timeSettingsMinutes: "នាទី",
        timeSettingsSeconds: "វិនាទី",
        logoPathTitle: "ផ្លូវថតនិមិត្តសញ្ញា",
        logoPathDesc: "ផ្លូវថតនិមិត្តសញ្ញាបច្ចុប្បន្នគឺ៖",
        logoPathHint: "កំណត់ផ្លូវថតនិមិត្តសញ្ញា",
        changelogTitle: "ប្រវត្តិធ្វើបច្ចុប្បន្នភាព",
        changelogContent: `
            <ul class="changelog-list">
                <li><h5>ជំនាន់ 2.5</h5>
                    <ul>
                        <li>បានផ្លាស់ទីការកំណត់ផ្លូវថតនិមិត្តសញ្ញាទៅក្នុង Popup មួយ។</li>
                        <li>បានបន្ថែមជម្រើសពណ៌ទីពីរសម្រាប់ក្រុមនីមួយៗ។</li>
                    </ul>
                </li>
                <li><h5>ជំនាន់ 2.4</h5>
                    <ul>
                        <li>ការកែប្រែ UI ដ៏ធំសម្រាប់ការควบคุมកម្មវិធីកំណត់ម៉ោងដោយផ្អែកលើមតិកែលម្អ។</li>
                        <li>បានបន្ថែមប៊ូតុង "រក្សាទុក & ធ្វើបច្ចុប្បន្នភាព" ដើម្បីអនុវត្តការផ្លាស់ប្តូរពេលវេលាភ្លាមៗ។</li>
                        <li>បានធ្វើឱ្យប្រសើរឡើងនូវភាពជឿជាក់នៃប៊ូតុង 'កំណត់ឡើងវិញទៅម៉ោងចាប់ផ្តើម' ។</li>
                    </ul>
                </li>
            </ul>`,
        toastLoadFileFirst: "សូមអាប់ឡូតឯកសារជាមុនសិន",
        toastMatchNotFound: "រកមិនឃើញ Match ID:",
        toastLoaded: "បានផ្ទុក ID:",
        toastSuccess: "ជោគជ័យ",
        toastSwapped: "បានប្តូរក្រុម",
        toastNoTextToCopy: "គ្មានអត្ថបទសម្រាប់ចម្លង",
        toastCopied: "បានចម្លងទៅក្ដារតម្បៀតខ្ទាស់",
        toastCopyFailed: "ការចម្លងបានបរាជ័យ",
        toastScoreReset: "បានកំណត់ពិន្ទុឡើងវិញ",
        toastSaved: "បានរក្សាទុក",
        toastObsError: "ការភ្ជាប់ទៅ OBS បានបរាជ័យ",
        toastInvalidTime: "ទម្រង់ម៉ោងមិនត្រឹមត្រូវ។ សូមពិនិត្យមើលនាទី និងវិនាទី (0-59)។",
        toastTimeSet: "បានកំណត់ម៉ោងចាប់ផ្តើម និងធ្វើបច្ចុប្បន្នភាពហើយ។",
    },
    // Brazilian Portuguese
    'pt-br': {
        appTitle: "Controlador de Placar de Futebol - V2.5",
        excel: "Excel",
        matchId: "ID:",
        load: "Carregar",
        teamA: "Equipe A",
        teamB: "Equipe B",
        edit: "Editar",
        editHint: "Edite o nome ou adicione uma nova linha com /",
        ok: "OK",
        label1: "Rótulo 1",
        label2: "Rótulo 2",
        label3: "Rótulo 3",
        swap: "Trocar Lados",
        reset: "Resetar",
        half: "Tempo",
        injuryTime: "Acréscimos",
        countdown: "Contagem",
        countdownHint: "Temporizador de contagem regressiva",
        resetToZeroHint: "Resetar cronômetro para 00:00",
        resetToStartHint: "Resetar cronômetro para o tempo inicial configurado",
        settings: "Config.",
        copy: "Copiar",
        help: "Ajuda",
        donate: "Apoiar",
        footerAppName: "OBS Dock UI Scoreboard",
        changelog: "Atualização da Versão 2.5",
        detailsTitle: "Configurações de Texto de Anúncio",
        detailsDesc: "Crie mensagens usando as tags abaixo para puxar dados automaticamente.",
        tagsTitle: "Tags Disponíveis",
        tagsList: [
            { code: '&lt;TeamA&gt;', desc: '- Nome da Equipe A' },
            { code: '&lt;TeamB&gt;', desc: '- Nome da Equipe B' },
            { code: '&lt;score_team_a&gt;', desc: '- Placar da Equipe A' },
            { code: '&lt;score_team_b&gt;', desc: '- Placar da Equipe B' },
            { code: '&lt;time_counter&gt;', desc: '- Tempo Atual (MM:SS)' },
            { code: '&lt;half_text&gt;', desc: '- Tempo (1st/2nd)' },
            { code: '&lt;label1&gt;', desc: '- Texto do Rótulo 1' },
            { code: '&lt;label2&gt;', desc: '- Texto do Rótulo 2' },
            { code: '&lt;label3&gt;', desc: '- Texto do Rótulo 3' },
        ],
        save: "Salvar",
        close: "Fechar",
        saveAndUpdate: "Salvar e Atualizar",
        helpTitle: "Como Usar",
        helpStep1: "1. Clique no ícone <i class='fas fa-folder-open'></i> para definir o caminho da pasta de logos. O padrão é <code>C:/OBSAssets/logos</code>.",
        helpStep2: "2. Clique no botão <i class='fas fa-file-excel'></i> Excel para selecionar o arquivo de dados.",
        helpStep3: "3. Selecione o ID da Partida desejado e clique em <i class='fas fa-check'></i> Carregar.",
        sourcesTitle: "Fontes OBS Necessárias",
        sourcesList: [
            { code: 'Color_Team_A', desc: '- **Fonte de Cor** para Equipe A (Primária)' },
            { code: 'Color_Team_B', desc: '- **Fonte de Cor** para Equipe B (Primária)' },
            { code: 'Color_Team_A_2', desc: '- **Fonte de Cor** para Equipe A (Secundária)' },
            { code: 'Color_Team_B_2', desc: '- **Fonte de Cor** para Equipe B (Secundária)' },
            { code: 'logo_team_a', desc: '- **Fonte de Imagem** para Logo da Equipe A' },
            { code: 'logo_team_b', desc: '- **Fonte de Imagem** para Logo da Equipe B' },
            { code: 'name_team_a', desc: '- **Texto (GDI+)** para Nome da Equipe A' },
            { code: 'name_team_b', desc: '- **Texto (GDI+)** para Nome da Equipe B' },
            { code: 'score_team_a', desc: '- **Texto (GDI+)** para Placar da Equipe A' },
            { code: 'score_team_b', desc: '- **Texto (GDI+)** para Placar da Equipe B' },
            { code: 'label_1', desc: '- **Texto (GDI+)** para Rótulo 1' },
            { code: 'label_2', desc: '- **Texto (GDI+)** para Rótulo 2' },
            { code: 'label_3', desc: '- **Texto (GDI+)** para Rótulo 3' },
            { code: 'half_text', desc: '- **Texto (GDI+)** para Tempo' },
            { code: 'time_counter', desc: '- **Texto (GDI+)** para Temporizador' },
            { code: 'injury_time_text', desc: '- **Texto (GDI+)** para Acréscimos (+1)' },
        ],
        understand: "Entendi",
        donateTitle: "Apoie-nos",
        donateThai: "Para Tailandeses (para o Placar)",
        donateForeign: "Para Estrangeiros (Fora da Tailândia)",
        timeSettingsTitle: "Definir Hora de Início",
        timeSettingsMinutes: "Minutos",
        timeSettingsSeconds: "Segundos",
        logoPathTitle: "Caminho da Pasta de Logos",
        logoPathDesc: "O caminho atual da pasta de logos é:",
        logoPathHint: "Definir caminho da pasta de logos",
        changelogTitle: "Histórico de Atualizações",
        changelogContent: `
            <ul class="changelog-list">
                <li><h5>Versão 2.5</h5>
                    <ul>
                        <li>Movida a configuração do caminho da pasta de logos para um pop-up dedicado.</li>
                        <li>Adicionada uma opção de cor secundária para cada equipe.</li>
                    </ul>
                </li>
                 <li><h5>Versão 2.4</h5>
                    <ul>
                        <li>Grande reformulação da interface do usuário para controles de timer com base no feedback.</li>
                        <li>Adicionado um botão "Salvar e Atualizar" para aplicar as alterações de tempo ao timer ao vivo imediatamente.</li>
                        <li>Melhorada a confiabilidade do botão "Resetar para o Início".</li>
                    </ul>
                </li>
            </ul>`,
        toastLoadFileFirst: "Por favor, carregue um arquivo primeiro",
        toastMatchNotFound: "ID da Partida não encontrado:",
        toastLoaded: "ID carregado:",
        toastSuccess: "Sucesso",
        toastSwapped: "Equipes trocadas",
        toastNoTextToCopy: "Nenhum texto para copiar",
        toastCopied: "Copiado para a área de transferência",
        toastCopyFailed: "Falha ao copiar",
        toastScoreReset: "Placar resetado",
        toastSaved: "Salvo",
        toastObsError: "Falha ao conectar ao OBS",
        toastInvalidTime: "Formato de hora inválido. Verifique minutos e segundos (0-59).",
        toastTimeSet: "A hora de início foi definida e atualizada.",
    },
    // Spanish
    es: {
        appTitle: "Controlador de Marcador de Fútbol - V2.5",
        excel: "Excel",
        matchId: "ID:",
        load: "Cargar",
        teamA: "Equipo A",
        teamB: "Equipo B",
        edit: "Editar",
        editHint: "Editar nombre o añadir línea con /",
        ok: "OK",
        label1: "Etiqueta 1",
        label2: "Etiqueta 2",
        label3: "Etiqueta 3",
        swap: "Cambiar Equipos",
        reset: "Reiniciar",
        half: "Periodo",
        injuryTime: "Tiempo añadido",
        countdown: "Regresiva",
        countdownHint: "Temporizador de cuenta regresiva",
        resetToZeroHint: "Reiniciar temporizador a 00:00",
        resetToStartHint: "Reiniciar temporizador al tiempo de inicio configurado",
        settings: "Ajustes",
        copy: "Copiar",
        help: "Ayuda",
        donate: "Donar",
        footerAppName: "OBS Dock UI Scoreboard",
        changelog: "Actualización Versión 2.5",
        detailsTitle: "Configuración de Texto de Anuncio",
        detailsDesc: "Crea un mensaje usando las etiquetas de abajo para obtener datos automáticamente.",
        tagsTitle: "Etiquetas Disponibles",
        tagsList: [
            { code: '&lt;TeamA&gt;', desc: '- Nombre Equipo A' },
            { code: '&lt;TeamB&gt;', desc: '- Nombre Equipo B' },
            { code: '&lt;score_team_a&gt;', desc: '- Marcador Equipo A' },
            { code: '&lt;score_team_b&gt;', desc: '- Marcador Equipo B' },
            { code: '&lt;time_counter&gt;', desc: '- Tiempo Actual (MM:SS)' },
            { code: '&lt;half_text&gt;', desc: '- Periodo (1st/2nd)' },
            { code: '&lt;label1&gt;', desc: '- Texto Etiqueta 1' },
            { code: '&lt;label2&gt;', desc: '- Texto Etiqueta 2' },
            { code: '&lt;label3&gt;', desc: '- Texto Etiqueta 3' },
        ],
        save: "Guardar",
        close: "Cerrar",
        saveAndUpdate: "Guardar y Actualizar",
        helpTitle: "Cómo Usar",
        helpStep1: "1. Haz clic en el ícono <i class='fas fa-folder-open'></i> para establecer la ruta de la carpeta de logos. Por defecto es <code>C:/OBSAssets/logos</code>.",
        helpStep2: "2. Haz clic en el botón <i class='fas fa-file-excel'></i> Excel para seleccionar el archivo de datos.",
        helpStep3: "3. Selecciona el ID del partido y haz clic en <i class='fas fa-check'></i> Cargar.",
        sourcesTitle: "Fuentes de OBS Requeridas",
        sourcesList: [
            { code: 'Color_Team_A', desc: '- **Fuente de Color** para Equipo A (Primario)' },
            { code: 'Color_Team_B', desc: '- **Fuente de Color** para Equipo B (Primario)' },
            { code: 'Color_Team_A_2', desc: '- **Fuente de Color** para Equipo A (Secundario)' },
            { code: 'Color_Team_B_2', desc: '- **Fuente de Color** para Equipo B (Secundario)' },
            { code: 'logo_team_a', desc: '- **Fuente de Imagen** para Logo Equipo A' },
            { code: 'logo_team_b', desc: '- **Fuente de Imagen** para Logo Equipo B' },
            { code: 'name_team_a', desc: '- **Texto (GDI+)** para Nombre Equipo A' },
            { code: 'name_team_b', desc: '- **Texto (GDI+)** para Nombre Equipo B' },
            { code: 'score_team_a', desc: '- **Texto (GDI+)** para Marcador Equipo A' },
            { code: 'score_team_b', desc: '- **Texto (GDI+)** para Marcador Equipo B' },
            { code: 'label_1', desc: '- **Texto (GDI+)** para Etiqueta 1' },
            { code: 'label_2', desc: '- **Texto (GDI+)** para Etiqueta 2' },
            { code: 'label_3', desc: '- **Texto (GDI+)** para Etiqueta 3' },
            { code: 'half_text', desc: '- **Texto (GDI+)** para Periodo' },
            { code: 'time_counter', desc: '- **Texto (GDI+)** para Temporizador' },
            { code: 'injury_time_text', desc: '- **Texto (GDI+)** para Tiempo añadido (+1)' },
        ],
        understand: "Entendido",
        donateTitle: "Apóyanos",
        donateThai: "Para usuarios de Tailandia",
        donateForeign: "Para usuarios internacionales",
        timeSettingsTitle: "Establecer Hora de Inicio",
        timeSettingsMinutes: "Minutos",
        timeSettingsSeconds: "Segundos",
        logoPathTitle: "Ruta de la Carpeta de Logos",
        logoPathDesc: "La ruta actual de la carpeta de logos es:",
        logoPathHint: "Establecer la ruta de la carpeta de logos",
        changelogTitle: "Historial de Actualizaciones",
        changelogContent: `
            <ul class="changelog-list">
                <li><h5>Versión 2.5</h5>
                    <ul>
                        <li>Se movió el ajuste de la ruta de la carpeta de logos a una ventana emergente dedicada.</li>
                        <li>Se agregó una opción de color secundario para cada equipo.</li>
                    </ul>
                </li>
                <li><h5>Versión 2.4</h5>
                    <ul>
                        <li>Revisión importante de la interfaz de usuario para los controles del temporizador basada en comentarios.</li>
                        <li>Se agregó un botón "Guardar y Actualizar" para aplicar los cambios de tiempo al temporizador en vivo de inmediato.</li>
                        <li>Mejora de la fiabilidad del botón "Reiniciar al Inicio".</li>
                    </ul>
                </li>
            </ul>`,
        toastLoadFileFirst: "Por favor, carga un archivo primero",
        toastMatchNotFound: "ID de partido no encontrado:",
        toastLoaded: "ID cargado:",
        toastSuccess: "Éxito",
        toastSwapped: "Equipos cambiados",
        toastNoTextToCopy: "No hay texto para copiar",
        toastCopied: "Copiado al portapapeles",
        toastCopyFailed: "Error al copiar",
        toastScoreReset: "Marcador reiniciado",
        toastSaved: "Guardado",
        toastObsError: "Fallo al conectar con OBS",
        toastInvalidTime: "Formato de hora no válido. Verifique los minutos y segundos (0-59).",
        toastTimeSet: "La hora de inicio ha sido establecida y actualizada.",
    }
};